# httpProxy: "http://127.0.0.1:10800"

# httpsProxy: "http://127.0.0.1:10800"

nodeLinker: node-modules

nmSelfReferences: false

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

unsafeHttpWhitelist:
  - 10.8.0.4

yarnPath: .yarn/releases/yarn-3.2.2.cjs
